spring.application.name=StockSyncApp
#vendorB.file-path=tmp/vendor-b/stock.csv
vendorB.file-path=${user.home}/StockSyncApp/StockSyncApp/tmp/vendor-b/stock.csv

# H2 DB configuration
spring.datasource.url=jdbc:h2:mem:stocksyncdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Auto create tables from JPA entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (accessible at http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
